### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [moehriegitt/hob3l#1]
I would like to point out that identifiers like “[`__CP_CSG2_TRIANGLE_H`](https://github.com/moehriegitt/hob3l/blob/301dc61abebd04106cc4cfd49d30dbba4ddf27bb/include/hob3l/csg2-triangle.h#L4 "Update candidate")” and “[`__cp_ring_replace`](https://github.com/moehriegitt/hob3l/blob/f9359459fedc40e29a67c80f42a85e30d87cdecb/include/hob3lbase/ring.h#L201 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by moehriegitt** [comment]
file and global scope done.  other scopes (mainly local variables in macros) still pending.

**Comment by moehriegitt** [comment]
fixed

**Comment by elfring** [comment]
Thanks for [your adjustment of affected identifiers](https://github.com/moehriegitt/hob3l/commit/3c3b2d0aea75c2ffe5e018b754ea78b6bc0f14c5 "Renaming of several identifiers").
