### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [moehriegitt/hob3l#2]
Would you like to add more error handling for return values from functions like the following?
- [cp_printf](https://github.com/moehriegitt/hob3l/blob/041059780b97400736d70301028b8822128b191d/include/hob3lbase/stream.h#L25 "Print formatted output.") ⇒ [cp_ps_doc_begin](https://github.com/moehriegitt/hob3l/blob/041059780b97400736d70301028b8822128b191d/src/ps.c#L61 "Prints document header.")
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [main](https://github.com/moehriegitt/hob3l/blob/51f1d1de488b04f84ff2374477b559d1634362c9/src/main.c#L630)

**Comment by moehriegitt** [comment]
Thanks for your valuable input. The issue should be fixed now.

**Comment by elfring** [comment]
Thanks for [your source code adjustments](https://github.com/moehriegitt/hob3l/commit/ae6fea0e9d7e8419fa529ccf15654ca645f728a8 "Check more errors").

-----

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
