### ISSUE TITLE
Assertion `((c->vert.size & 1) == 0) && "Odd number of edges meet in one point"' failed.

### ISSUE THREAD

**Issue by jepler** [moehriegitt/hob3l#5]
At 561197116dba5f82f79d6b58e8bb7129e2674571 (the current tip of master), this file provokes an assertion error: `hob3l.exe: src/csg2-bool.c:671: chain_flush_vertex: Assertion `((c->vert.size & 1) == 0) && "Odd number of edges meet in one point"' failed.`

[moe.zip](https://github.com/moehriegitt/hob3l/files/2753218/moe.zip)

**Comment by moehriegitt** [comment]
Unfortunately, this looks like a floating point instability that is still left. The plan is to fix it. For now, try tweaking the parameters a bit (see docs on command line parameters), or modify the input file a bit (as you may need to do also for OpenSCAD occasionally).

**Comment by moehriegitt** [comment]
The new version should fix this.
