### ISSUE TITLE
build failed for fontgen.exe

### ISSUE THREAD

**Issue by flegall2014** [moehriegitt/hob3l#7]
Hi. I'm building on Windows 10 using MinGW. Impossible to get fontgen to compile. Result from "make" in font directory is:

Thanks for helping out.

Best,

Franck

mv  libhob3lbase.a.new.a libhob3lbase.a
process_begin: CreateProcess(NULL, move libhob3lbase.a.new.a libhob3lbase.a, ...) failed.
make (e=2): Le fichier spécifié est introuvable.
make[1]: *** [libhob3lbase.a] Erreur 2
make[1]: quittant le répertoire « D:/projects/hob3l-master »
make: *** [all] Erreur 2

**Comment by moehriegitt** [comment]
The font is disabled for now. It may be reintegrated in the future.
