### ISSUE TITLE
Odd number of edges meet in one point

### ISSUE THREAD

**Issue by SteveC** [moehriegitt/hob3l#9]
Add this bug as a reproducible thing in case someone in the future works on hob3l, because it's awesome, and waiting for CGAL is painful sometimes :-)

shaft.scad:

`include <threads.scad>

// 54 threads
// length 3.5 inches
// outer diameter 1 inch

// about 2 threads missing from top and bottom so 56 threads over 3.5 inches = 16 threads / inch

inch_in_mm = 25.4;

difference() {
    english_thread(1 * 26.5 / 25.1, 16, 4);
    //cylinder(100, d=20);
    english_thread(0.8,16,1,internal=true);
    translate([0,0,inch_in_mm]) {
        //cylinder(4*inch_in_mm,d=22);
    }
}`

Uses threads library from here: https://www.dkprojects.net/openscad-threads/

Create csg:

`$ openscad shaft.scad -o shaft.csg
ECHO: "mm_diameter: 26.8167"
ECHO: "mm_pitch: 1.5875"
ECHO: "mm_length: 101.6"
ECHO: "mm_diameter: 20.32"
ECHO: "mm_pitch: 1.5875"
ECHO: "mm_length: 25.4"`

Run hob3l:

`$ ./hob3l.exe shaft.csg -o shaft.stl
Info: Z: min=0.1, step=0.2, layer_cnt=508, max=101.5
hob3l.exe: src/csg2-bool.c:705: chain_flush_vertex: Assertion `((c->vert.size & 1) == 0) && "Odd number of edges meet in one point"' failed.
Aborted`

**Comment by moehriegitt** [comment]
The new version should not fail anymore.
